version: "3.8"

services:
  jlapp:
    image: ghcr.io/Jorge09829985/jl:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jlapp.entrypoints=http"
        - "traefik.http.routers.jlapp.rule=Host(` `)"
        - "traefik.http.middlewares.jlapp-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.jlapp.middlewares=jlapp-https-redirect"
        - "traefik.http.routers.jlapp-secure.entrypoints=https"
        - "traefik.http.routers.jlapp-secure.rule=Host(`jl.byronrm.com`)"
        - "traefik.http.routers.jlapp-secure.tls=true"
        - "traefik.http.routers.jlapp-secure.tls.certresolver=http"
        - "traefik.http.routers.jlapp-secure.service=jlapp"
        - "traefik.http.services.jlapp.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
